[package]
name = "nex-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = { version = "0.5", default-features = false }
no_std_io = { git = "https://github.com/zaksabeast/no_std_io.git", rev = "5cf4b0e" }
safe-transmute = { version = "0.11", default-features = false }
arc4 = "0.1.0"
