name: Code checks

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tools
        run: rustup component add rustfmt

      - name: Format check
        run: cargo +nightly fmt --check

  lint-test:
    name: Lint and test
    runs-on: ubuntu-latest
    container: rust:slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tools
        run: rustup component add clippy

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test
